# this was generated by chatgpt as a quick help.

import struct

# Your 64-bit strings
data = [
    "0000000000000000000000000000000011000010010100000000000000000000",
    "0000000000000000000000000000000001000001110000000000000000000000",
    "0000000000000000000000100000000011000001111000000000000000000000",
    "0000000000000000000000000000000001000010011111000000000000000000",
    "0000000000000000000000100000000001000010000011000000000000000000"
]

def decode_float64bits(bits64):
    # Take the lower 32 bits
    bits32 = bits64[-32:]
    # Convert binary string to integer
    int_val = int(bits32, 2)
    # Pack into 4 bytes and unpack as float
    float_val = struct.unpack('>f', int_val.to_bytes(4, byteorder='big'))[0]
    return float_val

decoded = [decode_float64bits(b) for b in data]
print(decoded)
